#cloud-config
package_update: true
package_upgrade: true

# Install required packages
packages:
  - curl
  - wget
  - git
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

# Install Docker
runcmd:
  # Install Docker
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - usermod -aG docker ubuntu

  # Install Ollama
  - curl -fsSL https://ollama.com/install.sh | sh

  # Create n8n data directory
  - mkdir -p /opt/n8n/data
  - chown -R ubuntu:ubuntu /opt/n8n

  # Create Ollama systemd service
  - |
    cat > /etc/systemd/system/ollama.service << 'EOF'
    [Unit]
    Description=Ollama Service
    After=network-online.target

    [Service]
    Environment="OLLAMA_HOST=0.0.0.0"
    ExecStart=/usr/bin/ollama serve
    Restart=always
    RestartSec=3

    [Install]
    WantedBy=multi-user.target
    EOF

  # Create n8n systemd service
  - |
    cat > /etc/systemd/system/n8n.service << 'EOF'
    [Unit]
    Description=n8n workflow automation
    After=docker.service
    Requires=docker.service

    [Service]
    Type=simple
    User=ubuntu
    Environment=N8N_PORT=5678
    Environment=N8N_PROTOCOL=http
    Environment=NODE_ENV=production
    ExecStart=/usr/bin/docker run -d \
        --name n8n \
        -p 5678:5678 \
        -v /opt/n8n/data:/home/node/.n8n \
        -e N8N_PORT=5678 \
        -e N8N_PROTOCOL=http \
        -e NODE_ENV=production \
        --restart unless-stopped \
        docker.n8n.io/n8nio/n8n
    ExecStop=/usr/bin/docker stop n8n
    ExecStopPost=/usr/bin/docker rm n8n
    Restart=on-failure

    [Install]
    WantedBy=multi-user.target
    EOF

  # Start and enable services
  - systemctl daemon-reload
  - systemctl enable ollama
  - systemctl start ollama
  - systemctl enable n8n
  - systemctl start n8n

# Write a message to the console
final_message: "The system is finally up, after $UPTIME seconds" 